# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MantisExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MantisExample
  pod 'Mantis'

  target 'MantisExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
